// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsegztteepohifsohdjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZWd6dHRlZXBvaGlmc29oZGpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTA4NjgsImV4cCI6MjA1ODQ2Njg2OH0.nUc55dfBibMFG96SiYEYwZDvNtFXldx22pogFGctV5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);